### ISSUE TITLE
Read-me incomplete

### ISSUE THREAD

**Issue by DevOp77** [OtchereDev/django_orm#1]
Your Read-me doesn’t not include the commands for installing django filters and django crispy forms 

Solution
After running > env\Scripts\activate
run >pip install django-filters
run >pip install django-crispy-forms
And continue with read-me(that is; > cd orm_manage_user

**Comment by DevOp77** [comment]
The above solution solves issue with window Pc. I haven’t tried with Mac or Linux 
Thanks

**Comment by OtchereDev** [comment]
If you ran the command `pip install -r requirements.txt` like you wouldn't have faced that issue, I specified that in the Readme

**Comment by OtchereDev** [comment]
Okay I see the issue now, I missed the step for that I thought you will use the environment that was in the repo then you wouldn't need to run the command. But Readme will be works perfectly for Mac and Linux
